### ISSUE TITLE
Create Selection Page/Desired Information Selection

### ISSUE THREAD

**Issue by RJB888** [RJB888/iOS_Calm_the_Storm#6]
DoD:  A selection of disaster types is listed.  

User Story: As a user, I want to be able to see the list of disaster types to choose from.

**Comment by MikeTheGreat** [comment]
When reopening an issue please leave a comment briefly explaining why it's being reopened.
(Even if it was discussed in more detail in Slack it's good to leave a quick note here too)(and/or link to the Slack thread?  Can one do that?)
